export const API_CONFIG = {
  BASE_URL: "http://192.168.0.4:5030/",
  IMAGE_URL: "http://192.168.0.4:5030",
  // BASE_URL: "https://192.168.0.16:5030/",
  // IMAGE_URL: "https://api.geotree.in",
  // BASE_URL: "https://geotree-backend-8vxt.onrender.com/",
  // IMAGE_URL: "https://geotree-backend-8vxt.onrender.com",
  // baseurlCertificate: "https://geotree-backend-8vxt.onrender.com",
  TIMEOUT: 10000,
};

export const ENDPOINTS = {
  ADMIN_LOGIN: "api/admin/auth/login",
  ADMIN_STATS: "api/admin/stats",
  ADMIN_PROFILE: "api/admin/profile",
  STATES_LIST: "api/state/list",
  STATE_ADD: "api/state/add",
  STATE_UPDATE: "api/state/update",
  STATE_DELETE: "api/state/delete",
  PLANTATION_SITES_LIST: "api/site/sitelist",
  SITE_ADD: "api/site/add",
  SITE_UPDATE: "api/site/update",
  SITE_DELETE: "api/site/delete",
  SPECIES_LIST: "api/species/list",
  SPECIES_ADD: "api/species/add",
  SPECIES_UPDATE: "api/species/update",
  SPECIES_DELETE: "api/species/delete",
  CATEGORIES_LIST: "api/category/list",
  CATEGORY_ADD: "api/category/add",
  CATEGORY_UPDATE: "api/category/update",
  CATEGORY_DELETE: "api/category/delete",
  OCCASIONS_LIST: "api/occasion/list",
  OCCASION_ADD: "api/plantation/occasions/add",
  OCCASION_UPDATE: "api/plantation/occasions/update",
  OCCASION_DELETE: "api/plantation/occasions/delete",
  TOURNAMENTS_LIST: "api/ipl/tournaments/list",
  TOURNAMENT_ADD: "api/ipl/tournaments",
  TOURNAMENT_UPDATE: "api/ipl/tournaments",
  TOURNAMENT_DELETE: "api/ipl/tournaments/delete",
  TEAMS_LIST: "api/ipl/teams/list",
  TEAM_ADD: "api/ipl/teams",
  TEAM_UPDATE: "api/ipl/teams/update",
  TEAM_DELETE: "api/ipl/teams/delete",
  MATCHES_LIST: "api/ipl/matches/list",
  MATCH_ADD: "api/ipl/matches",
  MATCH_UPDATE: "api/ipl/matches/update",
  MATCH_DELETE: "api/ipl/matches/delete",
  NURSERIES_LIST: "api/master/nursery/list",
  NURSERY_ADD: "api/master/nursery/add",
  NURSERY_UPDATE: "api/master/nursery/update",
  NURSERY_DELETE: "api/master/nursery/delete",
  ADMINS_LIST: "api/admin/users/list",
  ADMIN_ADD: "api/admin/users",
  ADMIN_UPDATE: "api/admin/users/update",
  ADMIN_DELETE: "api/admin/users/delete",
  EMISSION_FACTORS_LIST: "api/carbon/emission-factors/list",
  EMISSION_FACTOR_ADD: "api/carbon/emission-factors/add",
  EMISSION_FACTOR_UPDATE: "api/carbon/emission-factors/update",
  EMISSION_FACTOR_DELETE: "api/carbon/emission-factors/delete",
  CARBON_FOOTPRINT_LIST: "api/admin-ui/models/Carbon/list",
  OCCASION_PLANTATIONS_LIST: "api/plantation/plantations/list/occasion",
  MATCH_PLANTATIONS_LIST: "api/plantation/plantations/list/ipl-match",
  TEAM_PLANTATIONS_LIST: "api/plantation/plantations/list/ipl-team",
  CARBON_PLANTATIONS_LIST: "api/plantation/plantations/list/carbon",
  PLANTATION_LIST: "api/plantation/plantations/list",
  PAYMENT_LIST: "api/payment/list",
  PAYMENT_DELETE: "api/payment/delete",
  CERTIFICATE_LIST: "api/certificate/list",
  CERTIFICATE_ADD: "api/certificate/generate",
  CERTIFICATE_UPDATE: "api/certificate/update",
  CERTIFICATE_DELETE: "api/certificate/delete",
  CERTIFICATE_TEMPLATE_ADD: "api/certificate-templates/add",
  CERTIFICATE_TEMPLATE_UPDATE: "api/certificate-templates/update",
  CERTIFICATE_TEMPLATE_DELETE: "api/certificate-templates/delete",
  SITE_INVENTORY_LIST: "api/site-inventory/list",
  CERTIFICATE_TEMPLATES_LIST: "api/certificate-templates/list",
  LOCATION_STATES: "api/location-data/states",
  REGENERATE_FORM: "api/plantation/occasions/regenerate-forms",
  LOCATION_DISTRICTS: "api/location-data/districts",
};
